{% set name = "openscm-twolayermodel" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a3d113310ddf260cb99c755dd3f5d972aecc1a98cd1744256edd79a514c99dec

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - scmdata >=0.9
    - tqdm

test:
  imports:
    - openscm_twolayermodel
  requires:
    - pip
  commands:
    - pip check
    - python -c "import openscm_twolayermodel; assert openscm_twolayermodel.__version__ == '{{ version }}'"

about:
  home: https://github.com/openscm/openscm-twolayermodel
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Implementations of the two layer radiative forcing driven models by Held et al. (2010), Geoffroy et al. (2013) and Bloch-Johnson et al. (2015)
  doc_url: https://openscm-two-layer-model.readthedocs.io/en/stable/
  dev_url: https://github.com/openscm/openscm-twolayermodel

extra:
  recipe-maintainers:
    - znicholls
